apiVersion: 1

datasources:
  - name: trainingpulse-pg
    uid: trainingpulse-pg
    type: grafana-postgresql-datasource
    access: proxy
    url: db:5432
    user: $POSTGRES_USER
    database: $POSTGRES_DB
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      sslmode: 'disable'
      postgresVersion: 16
    isDefault: true
    editable: true
