apiVersion: 1

datasources:
  - name: Nutrition
    uid: fddb-pg
    type: grafana-postgresql-datasource
    access: proxy
    url: db:5432
    user: $POSTGRES_USER
    database: fddb_nutrition
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      sslmode: disable
      postgresVersion: 16
    isDefault: false
    editable: true
